name: movie_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.7
  go_router: ^14.6.0
  get: ^4.6.6
  get_it: ^8.0.2
  dio: ^5.7.0
  url_launcher: ^6.3.1
  flutter_staggered_animations: ^1.1.1
  concentric_transition: ^1.0.3
  page_transition: ^2.1.0
  line_icons: ^2.0.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/


  # example:
  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
